/* 由 build.ps1 自动生成 —— 不要手改。
   换图：把 <slug>.png / .jpg 丢进 assets/images/<板块目录>/，
   然后双击根目录的「刷新图片.cmd」（或重跑 build.ps1）。
   占位图 <slug>.placeholder.svg 会自动让位，不用手动删。 */
window.JP_ASSETS = {
  "characters/caomeijiang": "assets/images/characters/caomeijiang.placeholder.svg",
  "characters/character-relations": "assets/images/characters/character-relations.placeholder.svg",
  "characters/doudou": "assets/images/characters/doudou.placeholder.svg",
  "characters/expression-sheet": "assets/images/characters/expression-sheet.placeholder.svg",
  "characters/la": "assets/images/characters/la.placeholder.svg",
  "characters/noote": "assets/images/characters/noote.placeholder.svg",
  "characters/oc-guidebook": "assets/images/characters/oc-guidebook.placeholder.svg",
  "characters/oc-lineup": "assets/images/characters/oc-lineup.placeholder.svg",
  "characters/oc-palette": "assets/images/characters/oc-palette.placeholder.svg",
  "characters/qi": "assets/images/characters/qi.placeholder.svg",
  "characters/silence-design": "assets/images/characters/silence-design.placeholder.svg",
  "characters/strawberry-sheet": "assets/images/characters/strawberry-sheet.placeholder.svg",
  "characters/tong": "assets/images/characters/tong.placeholder.svg",
  "characters/xiahua": "assets/images/characters/xiahua.placeholder.svg",
  "research/archive-plan": "assets/images/research/archive-plan.placeholder.svg",
  "research/image-read": "assets/images/research/image-read.placeholder.svg",
  "research/site-launch": "assets/images/research/site-launch.placeholder.svg",
  "research/the-word": "assets/images/research/the-word.placeholder.svg",
  "resources/archive-naming": "assets/images/resources/archive-naming.placeholder.svg",
  "resources/brush-pack": "assets/images/resources/brush-pack.placeholder.svg",
  "resources/fonts": "assets/images/resources/fonts.placeholder.svg",
  "resources/logos": "assets/images/resources/logos.placeholder.svg",
  "resources/rainbow-picturebook": "assets/images/resources/rainbow-picturebook.placeholder.svg",
  "resources/workspace": "assets/images/resources/workspace.placeholder.svg",
  "universe/architecture-spaces": "assets/images/universe/architecture-spaces.placeholder.svg",
  "universe/facade-rhythm": "assets/images/universe/facade-rhythm.placeholder.svg",
  "universe/map-legend": "assets/images/universe/map-legend.placeholder.svg",
  "universe/maps-geography": "assets/images/universe/maps-geography.placeholder.svg",
  "universe/noote-metro": "assets/images/universe/noote-metro.placeholder.svg",
  "universe/river-systems": "assets/images/universe/river-systems.placeholder.svg",
  "universe/scenery-light": "assets/images/universe/scenery-light.placeholder.svg",
  "universe/seasons-frame": "assets/images/universe/seasons-frame.placeholder.svg",
  "universe/station-naming": "assets/images/universe/station-naming.placeholder.svg",
  "universe/terrain-contours": "assets/images/universe/terrain-contours.placeholder.svg",
  "works/color-notes": "assets/images/works/color-notes.placeholder.svg",
  "works/doudou-seasons": "assets/images/works/doudou-seasons.placeholder.svg",
  "works/grid-system": "assets/images/works/grid-system.placeholder.svg",
  "works/indian-anklets": "assets/images/works/indian-anklets.placeholder.svg",
  "works/kyoto": "assets/images/works/kyoto.placeholder.svg",
  "works/linework": "assets/images/works/linework.placeholder.svg",
  "works/nanjing-station": "assets/images/works/nanjing-station.placeholder.svg",
  "works/negative-space": "assets/images/works/negative-space.placeholder.svg",
  "works/osaka": "assets/images/works/osaka.placeholder.svg",
  "works/paper-strip": "assets/images/works/paper-strip.placeholder.svg",
  "works/tongtong-mask": "assets/images/works/tongtong-mask.placeholder.svg",
  "works/type-scale": "assets/images/works/type-scale.placeholder.svg"
};