/* 由 build.ps1 自动生成 —— 不要手改。
   换图：把你的图存成同名文件盖掉 assets/images/<板块目录>/<slug>.*，
   刷新页面就生效，连构建都不用跑。
   要换成别的扩展名（png/jpg/webp…）才需要双击根目录的「刷新图片.cmd」
   （或重跑 build.ps1），让这份清单重排一次序。 */
window.JP_ASSETS = {
  "characters/caomeijiang": "assets/images/characters/caomeijiang.jpg",
  "characters/character-relations": "assets/images/characters/character-relations.jpg",
  "characters/doudou": "assets/images/characters/doudou.jpg",
  "characters/expression-sheet": "assets/images/characters/expression-sheet.jpg",
  "characters/la": "assets/images/characters/la.png",
  "characters/noote": "assets/images/characters/noote.jpg",
  "characters/oc-guidebook": "assets/images/characters/oc-guidebook.jpg",
  "characters/oc-lineup": "assets/images/characters/oc-lineup.jpg",
  "characters/oc-palette": "assets/images/characters/oc-palette.jpg",
  "characters/qi": "assets/images/characters/qi.jpg",
  "characters/silence-design": "assets/images/characters/silence-design.jpg",
  "characters/strawberry-sheet": "assets/images/characters/strawberry-sheet.jpg",
  "characters/tong": "assets/images/characters/tong.jpg",
  "characters/xiahua": "assets/images/characters/xiahua.jpg",
  "research/archive-plan": "assets/images/research/archive-plan.jpg",
  "research/image-read": "assets/images/research/image-read.jpg",
  "research/site-launch": "assets/images/research/site-launch.jpg",
  "research/the-word": "assets/images/research/the-word.jpg",
  "resources/archive-naming": "assets/images/resources/archive-naming.jpg",
  "resources/brush-pack": "assets/images/resources/brush-pack.jpg",
  "resources/fonts": "assets/images/resources/fonts.jpg",
  "resources/logos": "assets/images/resources/logos.jpg",
  "resources/rainbow-picturebook": "assets/images/resources/rainbow-picturebook.jpg",
  "resources/workspace": "assets/images/resources/workspace.jpg",
  "universe/architecture-spaces": "assets/images/universe/architecture-spaces.jpg",
  "universe/facade-rhythm": "assets/images/universe/facade-rhythm.jpg",
  "universe/map-legend": "assets/images/universe/map-legend.jpg",
  "universe/maps-geography": "assets/images/universe/maps-geography.jpg",
  "universe/noote-metro": "assets/images/universe/noote-metro.png",
  "universe/river-systems": "assets/images/universe/river-systems.jpg",
  "universe/scenery-light": "assets/images/universe/scenery-light.jpg",
  "universe/seasons-frame": "assets/images/universe/seasons-frame.jpg",
  "universe/station-naming": "assets/images/universe/station-naming.jpg",
  "universe/terrain-contours": "assets/images/universe/terrain-contours.jpg",
  "works/color-notes": "assets/images/works/color-notes.jpg",
  "works/doudou-seasons": "assets/images/works/doudou-seasons.jpg",
  "works/grid-system": "assets/images/works/grid-system.jpg",
  "works/indian-anklets": "assets/images/works/indian-anklets.jpg",
  "works/kyoto": "assets/images/works/kyoto.jpg",
  "works/linework": "assets/images/works/linework.jpg",
  "works/nanjing-station": "assets/images/works/nanjing-station.jpg",
  "works/negative-space": "assets/images/works/negative-space.jpg",
  "works/osaka": "assets/images/works/osaka.jpg",
  "works/paper-strip": "assets/images/works/paper-strip.jpg",
  "works/tongtong-mask": "assets/images/works/tongtong-mask.jpg",
  "works/type-scale": "assets/images/works/type-scale.jpg"
};